# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ddkkhaaa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ddkkhaaa-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 512
  timeout: 10
  environment:
    PORT: 8000

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-scripts

custom:
  serverless-offline:
    httpPort: 8000

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/client/libquery_engine-*'
  individually: true
